nelmio_api_doc:
    documentation:
        info:
            title: Technical Test SISMIC
            description: This an app for a technical test for SISMIC
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
